name: WebUI Action

on:
    workflow_dispatch:
        inputs:
            productpath:
                description: 'Product Path'
                required: true
            imshared:
                description: 'IMShared Location'
                required: true
            workspace:
                description: 'Workspace
                required: true
            project:
                description: 'Project'
                required: true
            suite:
                description: 'Test Suite Name'
                required: true

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: Execute WebUI Test
        steps:
         - name: Execute Test
           uses: SonaHJ/WebUIAction@main
           with:
            productpath: '${{ github.event.inputs.productpath }}'
            imshared: '${{ github.event.inputs.imshared }}'
            workspace: '${{ github.event.inputs.workspace }}'
            project: '${{ github.event.inputs.project }}'
            suite: '${{ github.event.inputs.suite }}'